### ISSUE TITLE
SFTP Direktverbindung von VS Code zum Pi

### ISSUE THREAD

**Issue by Makapre** [BOOM21/dashboard#1]
Hallo,
ich habe Deine Streams gesehen und Du lädst die Dateien immer von Hand auf den Pi.
Ich kenne ein gutes VS Code Plugin, was mittels [SFTP](https://marketplace.visualstudio.com/items?itemName=liximomo.sftp) die Änderungen direkt an den Pi sendet. 
Das Setup ist nicht wirklich kompliziert und vielleicht hilft es Dir den Workflow zu vereinfachen.

**Comment by BOOM21** [comment]
Hey, verdammt coole Sache, habe ich direkt eingerichtet, das spart den Arbeitsschritt und wird mir auch außerhalb des Stream helfen. Vielen dank dafür. Ich hoffe du schaust am Freitag nochmal rein, dann kannst du es auch in Benutzung sehen ;D Ansonsten noch viel Spaß weiterhin mit den Streams

**Comment by Makapre** [comment]
Freut mich!
Ich hoffe Freitag kann ich, sonst guck ich mir aber auch gerne die Streams im Nachhinein an, wenn ich Zeit habe.
